[package]
name = "webview2_test"
version = "0.1.0"
authors = ["Itay <naveh.itay@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.3.1"
winapi = "0.3.9"
winit = "0.24.0"
webview2 = "0.1.0"
